In [5]:
import pandas as pd
from pathlib import Path
import pickle
import yfinance as yf

In [6]:
app_data_location = Path(".").resolve().parent.joinpath('global_app').joinpath('global_data.sav')
app_data = {}

In [7]:
df = pd.read_excel(Path(".").resolve().parent.joinpath('data').joinpath(r'CI Select Global Equity - Dec 31, 2021 Holdings Report.xlsx'))
df

,Fund Code,Fund Name,Symbol,Name,CUSIP,SEDOL,RT ID,Quantity,Price,Exchange Rate,Market Value,Currency,MSCI GICS Code,MSCI GICS Category,Major Asset Code,Minor Asset Code,Country Code,Country Name
0,654,654 - CI Select Global Equity Fund,CAD,Canadian Dollar,NaN,NaN,CAD,8.717886e+05,1.000000,1.00000,926102.55,CAD,NaN,UNCLASSIFIED,CURR,Currency,NaN,NaN
1,654,654 - CI Select Global Equity Fund,USD,US Dollar,NaN,NaN,USD,5.380167e+06,1.000000,0.78453,6857822.14,USD,NaN,UNCLASSIFIED,CURR,Currency,NaN,NaN
2,654,654 - CI Select Global Equity Fund,USD/CAD Fwd,Sell USD Buy CAD Forward (Various Contracts < ...,NaN,NaN,Quantity expressed in CAD,-4.929453e+07,0.784553,0.78453,-676116.00,USD,NaN,UNCLASSIFIED,DERIV,Currency Forward,NaN,NaN
3,654,654 - CI Select Global Equity Fund,USDCADUSD2022012079_FX,Buy USD Sell CAD (Various Contracts < 1mo),NaN,NaN,Quantity expressed in USD,2.049293e+07,1.274611,1.00000,786962.37,CAD,NaN,UNCLASSIFIED,DERIV,Currency Forward,NaN,NaN
4,654,654 - CI Select Global Equity Fund,EUR,European Euro,NaN,NaN,EUR,8.050500e+03,1.000000,0.69302,11616.55,EUR,NaN,UNCLASSIFIED,CURR,Currency,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,654,654 - CI Select Global Equity Fund,NEE US,NEXTERA ENERGY INC,65339F101,2328915,65339F101,2.161600e+04,92.770000,0.78453,2556073.47,USD,5510.0,UTILITIES,EQTY,Common Stock,USA,United States
121,654,654 - CI Select Global Equity Fund,OGE US,OGE Energy Corp.,670837103,2657802,670837103,3.456900e+04,38.250000,0.78453,1685422.16,USD,5510.0,UTILITIES,EQTY,Common Stock,USA,United States
122,654,654 - CI Select Global Equity Fund,SRE US,SEMPRA ENERGY,816851109,2138158,816851109,1.040600e+04,131.770000,0.78453,1747796.29,USD,5510.0,UTILITIES,EQTY,Common Stock,USA,United States
123,654,654 - CI Select Global Equity Fund,COLD US,AMERICOLD REALTY TRUST,03064D108,B3SKZK7,03064D108,4.613300e+04,32.890000,0.78453,1934042.51,USD,6010.0,Real Estate,EQTY,Common Stock,USA,United States
124,654,654 - CI Select Global Equity Fund,PLD US,PROLOGIS INC,74340W103,B44WZD7,74340W103,1.716200e+04,167.970000,0.78453,3674430.73,USD,6010.0,Real Estate,EQTY,Real Estate Investment Trust,USA,United States

In [8]:
df['weight'] = df['Market Value'] / df['Market Value'].sum()
df

,Fund Code,Fund Name,Symbol,Name,CUSIP,SEDOL,RT ID,Quantity,Price,Exchange Rate,Market Value,Currency,MSCI GICS Code,MSCI GICS Category,Major Asset Code,Minor Asset Code,Country Code,Country Name,weight
0,654,654 - CI Select Global Equity Fund,CAD,Canadian Dollar,NaN,NaN,CAD,8.717886e+05,1.000000,1.00000,926102.55,CAD,NaN,UNCLASSIFIED,CURR,Currency,NaN,NaN,0.002358
1,654,654 - CI Select Global Equity Fund,USD,US Dollar,NaN,NaN,USD,5.380167e+06,1.000000,0.78453,6857822.14,USD,NaN,UNCLASSIFIED,CURR,Currency,NaN,NaN,0.017462
2,654,654 - CI Select Global Equity Fund,USD/CAD Fwd,Sell USD Buy CAD Forward (Various Contracts < ...,NaN,NaN,Quantity expressed in CAD,-4.929453e+07,0.784553,0.78453,-676116.00,USD,NaN,UNCLASSIFIED,DERIV,Currency Forward,NaN,NaN,-0.001722
3,654,654 - CI Select Global Equity Fund,USDCADUSD2022012079_FX,Buy USD Sell CAD (Various Contracts < 1mo),NaN,NaN,Quantity expressed in USD,2.049293e+07,1.274611,1.00000,786962.37,CAD,NaN,UNCLASSIFIED,DERIV,Currency Forward,NaN,NaN,0.002004
4,654,654 - CI Select Global Equity Fund,EUR,European Euro,NaN,NaN,EUR,8.050500e+03,1.000000,0.69302,11616.55,EUR,NaN,UNCLASSIFIED,CURR,Currency,NaN,NaN,0.000030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,654,654 - CI Select Global Equity Fund,NEE US,NEXTERA ENERGY INC,65339F101,2328915,65339F101,2.161600e+04,92.770000,0.78453,2556073.47,USD,5510.0,UTILITIES,EQTY,Common Stock,USA,United States,0.006508
121,654,654 - CI Select Global Equity Fund,OGE US,OGE Energy Corp.,670837103,2657802,670837103,3.456900e+04,38.250000,0.78453,1685422.16,USD,5510.0,UTILITIES,EQTY,Common Stock,USA,United States,0.004291
122,654,654 - CI Select Global Equity Fund,SRE US,SEMPRA ENERGY,816851109,2138158,816851109,1.040600e+04,131.770000,0.78453,1747796.29,USD,5510.0,UTILITIES,EQTY,Common Stock,USA,United States,0.004450
123,654,654 - CI Select Global Equity Fund,COLD US,AMERICOLD REALTY TRUST,03064D108,B3SKZK7,03064D108,4.613300e+04,32.890000,0.78453,1934042.51,USD,6010.0,Real Estate,EQTY,Common Stock,USA,United States,0.004925
124,654,654 - CI Select Global Equity Fund,PLD US,PROLOGIS INC,74340W103,B44WZD7,74340W103,1.716200e+04,167.970000,0.78453,3674430.73,USD,6010.0,Real Estate,EQTY,Real Estate Investment Trust,USA,United States,0.009356

In [9]:
top_holding_df = df.sort_values(by='weight', ascending=False).head(10)
top_holding_df

,Fund Code,Fund Name,Symbol,Name,CUSIP,SEDOL,RT ID,Quantity,Price,Exchange Rate,Market Value,Currency,MSCI GICS Code,MSCI GICS Category,Major Asset Code,Minor Asset Code,Country Code,Country Name,weight
108,654,654 - CI Select Global Equity Fund,AMD US,ADVANCED MICRO DEVICES,7903107,2007849,2007849,81282.000,145.150,0.78453,15038408.09,USD,4530.0,SEMICONDUCTORS & SEMICONDUCTOR EQUIPMENT,EQTY,Common Stock,USA,United States,0.038291
101,654,654 - CI Select Global Equity Fund,MSFT US,MICROSOFT CORP,594918104,2588173,594918104,28102.000,339.320,0.78453,12154500.96,USD,4510.0,SOFTWARE & SERVICES,EQTY,Common Stock,USA,United States,0.030948
107,654,654 - CI Select Global Equity Fund,AAPL US,APPLE INC,37833100,2046251,2046251,47928.000,178.200,0.78453,10886479.29,USD,4520.0,TECHNOLOGY HARDWARE & EQUIPMENT,EQTY,Common Stock,USA,United States,0.027720
112,654,654 - CI Select Global Equity Fund,STM FP,STMICROELECTRONICS NV,NaN,5962332,5962332,149367.000,43.740,0.69302,9427307.41,EUR,4530.0,SEMICONDUCTORS & SEMICONDUCTOR EQUIPMENT,EQTY,Common Stock,NLD,Netherlands,0.024004
111,654,654 - CI Select Global Equity Fund,NVDA US,NVIDIA CORP,67066G104,2379504,2379504,24847.000,295.860,0.78453,9370238.77,USD,4530.0,SEMICONDUCTORS & SEMICONDUCTOR EQUIPMENT,EQTY,Common Stock,USA,United States,0.023859
15,654,654 - CI Select Global Equity Fund,AAL LN,ANGLO AMERICAN USD0.54945(POST CONSOL,NaN,B1XZS82,B1XZS82,139561.000,30.195,0.58131,7249220.54,GBP,1510.0,MATERIALS,EQTY,Common Stock,GBR,United Kingdom,0.018458
12,654,654 - CI Select Global Equity Fund,RDSA LN,ROYAL DUTCH SHELL PLC-A SHS,NaN,B03MLX2,B03MLX2,253041.000,16.190,0.58131,7047416.68,GBP,1010.0,ENERGY,EQTY,Common Stock,GBR,United Kingdom,0.017944
1,654,654 - CI Select Global Equity Fund,USD,US Dollar,NaN,NaN,USD,5380167.201,1.000,0.78453,6857822.14,USD,NaN,UNCLASSIFIED,CURR,Currency,NaN,NaN,0.017462
41,654,654 - CI Select Global Equity Fund,6758 JT,SONY CORP JPY50,J76379106,6821506,6821506,39897.000,14475.000,90.27979,6396881.02,JPY,2520.0,CONSUMER DURABLES & APPAREL,EQTY,Common Stock,JPN,Japan,0.016288
91,654,654 - CI Select Global Equity Fund,SYF US,SYNCHRONY FINANCIAL,87165B103,BP96PS6,87165B103,103448.000,46.260,0.78453,6099836.18,USD,4020.0,DIVERSIFIED FINANCIALS,EQTY,Common Stock,USA,United States,0.015532

In [10]:
app_data['top_holding_df'] = top_holding_df

In [12]:
ydata = yf.download("VCR VGT", start="2022-01-01", end="2022-05-31")
ydata['Adj Close']

[*********************100%***********************]  2 of 2 completed

                   VCR         VGT
Date
2022-01-03  347.019043  460.387543
2022-01-04  345.494354  454.567932
2022-01-05  335.628784  439.480743
2022-01-06  334.971100  437.816620
2022-01-07  329.450317  433.342255
...                ...         ...
2022-05-23  235.141541  344.290894
2022-05-24  228.494492  337.633057
2022-05-25  235.920013  342.474213
2022-05-26  247.168076  351.158325
2022-05-27  255.032745  363.395966

[102 rows x 2 columns]

In [13]:
sector_df = ydata['Adj Close'].pct_change().fillna(0)
sector_df

                 VCR       VGT
Date
2022-01-03  0.000000  0.000000
2022-01-04 -0.004394 -0.012641
2022-01-05 -0.028555 -0.033190
2022-01-06 -0.001960 -0.003787
2022-01-07 -0.016481 -0.010220
...              ...       ...
2022-05-23  0.005077  0.021168
2022-05-24 -0.028268 -0.019338
2022-05-25  0.032498  0.014339
2022-05-26  0.047677  0.025357
2022-05-27  0.031819  0.034849

[102 rows x 2 columns]

In [14]:
sector_df['tech-cons'] = sector_df['VGT'] - sector_df['VCR']
sector_diff_df = (sector_df['tech-cons'] + 1).cumprod() - 1
sector_diff_df = sector_diff_df.reset_index()
sector_diff_df

          Date  tech-cons
0   2022-01-03   0.000000
1   2022-01-04  -0.008247
2   2022-01-05  -0.012844
3   2022-01-06  -0.014648
4   2022-01-07  -0.008478
..         ...        ...
97  2022-05-23   0.098231
98  2022-05-24   0.108038
99  2022-05-25   0.087917
100 2022-05-26   0.063635
101 2022-05-27   0.066858

[102 rows x 2 columns]

In [ ]:
app_data['sector_diff_df'] = sector_diff_df

In [11]:
pickle.dump(app_data, open(app_data_location, 'wb'))